import mapInfoStore from "./mapInfoStore";
import loadingStore from "./loadingStore";
import mapSAHInfoStore from "./mapSAHInfoStore";
import mapAvailableDatesStore from "./mapAvailableDatesStore";
import riskPropertiesStore from "./riskPropertiesStore";
import sahChartStore from "./sahChartStore";
import playerStore from "./playerStore";
import menuStore from "./menus";
import menuSelectionStore from "./menuSelectionStore";
import endpointStore from "./endpointStore";

export const createMapInfoStore = mapInfoStore;
export const createLoadingStore = loadingStore;
export const createMapSAHInfoStore = mapSAHInfoStore;
export const createAvailableDatesStore = mapAvailableDatesStore;
export const createMenuSelectionStore = menuSelectionStore;
export const createRiskPropertiesStore = riskPropertiesStore;
export const createSahChartStore = sahChartStore;
export const createPlayerStore = playerStore;
export const createMenusStore = menuStore;
export const createEndpointStore = endpointStore;
